# https://github.com/pashky/restclient.el

:token = eyJhbGciOiJIUzI1NiJ9.eyJ0ZWFjaGVyX2lkIjoxfQ.om35XTNV_AqVREcEUXCXq7BcVBjUZI6w_kS-SnG09BE

# sign up (create teacher)

POST http://localhost:3000/v1/teachers
Content-Type: application/json

{
  "teacher": {
    "email": "p@h.com",
    "password": "p",
    "password_confirmation": "p"
  }
}

# login

POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "teacher": {
    "email": "edna@springfield.edu",
    "password": "password"
  }
}

# validate

GET http://localhost:3000/v1/validate
Content-Type: application/json
Authorization: :token

# index stories

GET http://localhost:3000/v1/stories
Content-Type: application/json

# show story

GET http://localhost:3000/v1/stories/1
Content-Type: application/json

# post reading

POST http://localhost:3000/v1/readings
Content-Type: application/json
Authorization: :token

{
"reading": {
    "student_id": "5",
    "story_id": 1,
    "mistakes": [
        {
            "storyWordId": 10,
            "category": "Miscorrection",
            "miscue": "asdf"
        },
        {
            "storyWordId": 49,
            "category": "Hesitation",
            "miscue": null
        }
    ]
}
}

# index readings

GET http://localhost:3000/v1/readings
Content-Type: application/json
Authorization: :token

# create student
POST http://localhost:3000/v1/students
Content-Type: application/json
Authorization: :token

{
    "student": {
        "name": "New Bloggs"
    }
}
